import os

from django.core import mail


def debug_print_last_email() -> None:
    if os.getenv("TEST_EMAILS_CONSOLE") == "true":
        print(getattr(mail, "outbox")[-1].message())


def reusable_captcha_key() -> str:
    # generated by `secrets.token_urlsafe()`
    return "XOuZynTK0uP3jAhN2rZ9JkC6tnSLmXidLkjqIxgoHU8"


def reusable_captcha_seed() -> str:
    # generated by `secrets.token_hex()`
    return "66ba106a3612438180e5b1711dd28cd2dc9365c107960f43c28c1477c27f1f40"
