version: "3.9"
services:
  rss_temple:
    image: rss_temple:latest
    build:
      context: .
      args:
        APP_ENVIRONMENT: dev
    env_file:
      - .env
    command: >
      sh -c "while ! python manage.py test_ready; do
              sleep 0.1
            done

            python manage.py migrate

            daphne -b 0.0.0.0 -p 8001 rss_temple.asgi:application
            "
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/rss_temple/
  rss_temple_daemon_feed_scrapper:
    image: rss_temple:latest
    build:
      context: .
      args:
        APP_ENVIRONMENT: dev
    command: >
      sh -c "while ! python manage.py test_ready; do
              sleep 0.1
            done

            python manage.py feed_scrapper_daemon
            "
    depends_on:
      - postgres
    volumes:
      - ./:/rss_temple/
  rss_temple_daemon_notify:
    image: rss_temple:latest
    build:
      context: .
      args:
        APP_ENVIRONMENT: dev
    command: >
      sh -c "while ! python manage.py test_ready; do
              sleep 0.1
            done

            python manage.py notify_daemon
            "
    depends_on:
      - postgres
    volumes:
      - ./:/rss_temple/
  rss_temple_subscription_setup:
    image: rss_temple:latest
    build:
      context: .
      args:
        APP_ENVIRONMENT: dev
    command: >
      sh -c "while ! python manage.py test_ready; do
              sleep 0.1
            done

            python manage.py subscription_setup_daemon
            "
    depends_on:
      - postgres
    volumes:
      - ./:/rss_temple/
  redis:
    image: redis:7
  postgres:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/data
  caddy:
    image: caddy:2
    ports:
      - "80:80"
    volumes:
      - caddy_data:/data
volumes:
  postgres_data:
  caddy_data:
