services:
  valkey:
    image: valkey/valkey:8-alpine
    networks:
      - rss_temple_net
  postgresql:
    image: postgres:17-alpine
    shm_size: '256m'
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rss_temple_net
  caddy:
    image: caddy:2-alpine
    ports:
      - '8000:8000'
    volumes:
      - caddy_data:/data/
      - django_static:/static/
    networks:
      - default
      - rss_temple_net
  rss_temple:
    env_file:
      - .env
    volumes:
      - django_static:/code/_static/
    networks:
      - default  # necessary, because functionality requires making calls to the external internet
      - rss_temple_net
  rss_temple_dramatiq:
    env_file:
      - .env
    networks:
      - default  # necessary, because functionality requires making calls to the external internet
      - rss_temple_net
  rss_temple_schedulerdaemon:
    env_file:
      - .env
    networks:
      - rss_temple_net
volumes:
  db_data:
  caddy_data:
  django_static:
networks:
  rss_temple_net:
    internal: true
