version: '3.9'

services:
  redis:
    image: redis
  postgresql:
    image: postgres:15
    shm_size: '256m'
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
  caddy:
    image: caddy:2
    ports:
      - '8000:8000'
    volumes:
      - caddy_data:/data/
      - django_static:/static/
  rss_temple:
    env_file:
      - .env
    volumes:
      - django_static:/code/_static/
  rss_temple_feedscrapperdaemon:
    env_file:
      - .env
  rss_temple_subscriptionsetupdaemon:
    env_file:
      - .env
  rss_temple_archivefeedentriesdaemon:
    env_file:
      - .env
volumes:
  db_data:
  caddy_data:
  django_static:
