services:
  caddy:
    volumes:
      - ./webserver/Caddyfile.dev:/etc/caddy/Caddyfile
  rss_temple:
    image: rss_temple
    command: >
      sh -c "
        while ! python ./manage.py checkready; do
          sleep 0.1
        done

        python ./manage.py collectstatic --noinput &

        python ./manage.py migrate

        exec watchmedo auto-restart --directory=/code/ --pattern=*.py --ignore-patterns=**/.venv/* --recursive -- \\
          daphne -b 0.0.0.0 -p 8000 rss_temple.asgi:application
      "
    build:
      context: ./
    environment:
      APP_IN_DOCKER: 'true'
      # jemalloc configuration. See https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md
      MALLOC_CONF: background_thread:true,max_background_threads:1,metadata_thp:auto,dirty_decay_ms:30000,muzzy_decay_ms:30000
    expose:
      - '8000'
    volumes:
      - ./:/code/
  rss_temple_dramatiq:
    image: rss_temple
    command: dramatiq --watch . api_dramatiq.tasks -Q rss_temple
    build:
      context: ./
    environment:
      APP_IN_DOCKER: 'true'
      # jemalloc configuration. See https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md
      MALLOC_CONF: background_thread:true,max_background_threads:1,metadata_thp:auto,dirty_decay_ms:30000,muzzy_decay_ms:30000
    volumes:
      - ./:/code/
  rss_temple_schedulerdaemon:
    image: rss_temple
    command: >
      sh -c "
        while ! python ./manage.py checkready; do
          sleep 0.1
        done

        while ! python ./manage.py migrate --check; do
          sleep 5
        done

        python ./manage.py checkclassifierlabels

        exec watchmedo auto-restart --directory=/code/ --pattern=*.py --ignore-patterns=**/.venv/* --recursive -- \\
          python ./manage.py schedulerdaemon
      "
    build:
      context: ./
    environment:
      APP_IN_DOCKER: 'true'
      # jemalloc configuration. See https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md
      MALLOC_CONF: background_thread:true,max_background_threads:1,metadata_thp:auto,dirty_decay_ms:30000,muzzy_decay_ms:30000
    volumes:
      - ./:/code/
