FROM python:3.10-slim
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
RUN pip install pipenv
ENV PIPENV_VENV_IN_PROJECT 1
COPY . .
RUN pipenv install --deploy
