[tool.isort]
profile = "black"

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
check_untyped_defs = true

[tool.django-stubs]
django_settings_module = "rss_temple.settings"

[[tool.mypy.overrides]]
module = [
    "feedparser",
    "validators",
    "quick_email",
    "defusedxml.*",
    "url_normalize",
    "allauth.*",
    "dj_rest_auth.*",
    "apscheduler.*",
    "django_apscheduler.*",
    "redis_lock.*",
]
ignore_missing_imports = true
