"""Pure-Python inference for the trained classifier.

MUST NOT be imported from `api/views/`. It is loaded lazily inside the dramatiq
task so the model lives in exactly one process rather than in every gunicorn
worker. `api/tests/test_text_classifier.py` enforces this.

The tokenization and TF-IDF weighting here must match scikit-learn's
TfidfVectorizer exactly, because the vocabulary was fitted by scikit-learn and
this code has to reproduce the same feature indices. Divergence fails silently:
mismatched terms simply miss the vocabulary lookup and vanish. The parity
fixtures generated by `scripts/train_classifier.py` are what catch it.
"""

import math
import re
from array import array
from collections import Counter
from functools import lru_cache
from typing import NamedTuple

from api.text_classifier.artifact import Artifact, VectorizerConfig


class Prediction(NamedTuple):
    label: str
    score: float
    probability: float


@lru_cache(maxsize=4)
def _token_re(pattern: str) -> re.Pattern[str]:
    return re.compile(pattern)


def sigmoid(x: float) -> float:
    if x >= 0.0:
        return 1.0 / (1.0 + math.exp(-x))
    exp_x = math.exp(x)
    return exp_x / (1.0 + exp_x)


def analyze(text: str, vectorizer: VectorizerConfig) -> list[str]:
    """Reproduce scikit-learn's word analyzer.

    Order is load-bearing: lowercase, tokenize, remove stop words, THEN build
    bigrams. Building bigrams before removing stop words produces a different
    feature set ("the cat" instead of "cat dog") and silently degrades scoring.
    """
    if vectorizer.lowercase:
        text = text.lower()

    tokens = _token_re(vectorizer.token_pattern).findall(text)

    stop_words = set(vectorizer.stop_words)
    if stop_words:
        tokens = [t for t in tokens if t not in stop_words]

    min_n, max_n = vectorizer.ngram_range
    terms: list[str] = list(tokens) if min_n == 1 else []

    n_tokens = len(tokens)
    for n in range(max(min_n, 2), min(max_n, n_tokens) + 1):
        for i in range(n_tokens - n + 1):
            terms.append(" ".join(tokens[i : i + n]))

    return terms


def _tfidf(artifact: Artifact, text: str) -> dict[int, float]:
    """Sparse L2-normalised TF-IDF vector, keyed by feature index."""
    counts = Counter(
        artifact.vocabulary[term]
        for term in analyze(text, artifact.vectorizer)
        if term in artifact.vocabulary
    )
    if not counts:
        return {}

    vector: dict[int, float] = {}
    for index, count in counts.items():
        tf = 1.0 + math.log(count) if artifact.vectorizer.sublinear_tf else float(count)
        vector[index] = tf * artifact.idf[index]

    norm = math.sqrt(sum(value * value for value in vector.values()))
    if norm > 0.0:
        for index in vector:
            vector[index] /= norm

    return vector


def decision_scores(artifact: Artifact, text: str) -> list[float]:
    """Raw one-vs-rest decision score per label, in artifact.labels order."""
    vector = _tfidf(artifact, text)
    n_features = len(artifact.vocabulary)
    # `coef` must be C-order / row-major / label-major: coef[label_index *
    # n_features + feature_index]. See the docstring on `Artifact.coef` in
    # artifact.py -- a Fortran-order ravel has the same length and would
    # not be caught by any check, only by scoring every label with the
    # wrong coefficients.
    coef: array = artifact.coef

    scores: list[float] = []
    for label_index in range(len(artifact.labels)):
        offset = label_index * n_features
        total = float(artifact.intercept[label_index])
        for feature_index, value in vector.items():
            total += value * coef[offset + feature_index]
        scores.append(total)

    return scores


def predict(artifact: Artifact, text: str, max_labels: int) -> list[Prediction]:
    scores = decision_scores(artifact, text)

    predictions = [
        Prediction(
            label=artifact.labels[i],
            score=score,
            probability=sigmoid(score),
        )
        for i, score in enumerate(scores)
        if score >= artifact.thresholds[i]
    ]
    predictions.sort(key=lambda p: p.score, reverse=True)
    # A negative max_labels would otherwise silently slice from the end
    # (predictions[:-1] drops the last entry instead of returning nothing),
    # so clamp to zero rather than pass a negative straight to slicing.
    return predictions[: max(max_labels, 0)]
