# Generated by Django 2.1.7 on 2019-03-10 18:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacebookLogin",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("profile_id", models.CharField(max_length=96)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FavoriteFeedEntryUserMapping",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("feed_url", models.TextField(unique=True)),
                ("title", models.TextField()),
                ("home_url", models.TextField(null=True)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "db_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("db_updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeedEntry",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.TextField(null=True)),
                ("created_at", models.DateTimeField(null=True)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(null=True)),
                ("title", models.TextField(null=True)),
                ("url", models.TextField(null=True)),
                ("content", models.TextField(null=True)),
                ("author_name", models.TextField(null=True)),
                ("hash", models.IntegerField()),
                (
                    "db_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("db_updated_at", models.DateTimeField(null=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Feed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedEntryTagMapping",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "feed_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.FeedEntry"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedSubscriptionProgressEntry",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Not Started"), (1, "Started"), (2, "Finished")],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedSubscriptionProgressEntryDescriptor",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("feed_url", models.TextField()),
                ("custom_feed_title", models.TextField(null=True)),
                ("user_category_text", models.TextField(null=True)),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "feed_subscription_progress_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.FeedSubscriptionProgressEntry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedTagMapping",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Feed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedUserCategoryMapping",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Feed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoogleLogin",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("g_user_id", models.CharField(max_length=96)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MyLogin",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("pw_hash", models.CharField(max_length=96)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ReadFeedEntryUserMapping",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("read_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "feed_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.FeedEntry"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("expires_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubscribedFeedUserMapping",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("custom_feed_title", models.TextField(null=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Feed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("label_text", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="UserCategory",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.User"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.User"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="subscribedfeedusermapping",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.User"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.User"
            ),
        ),
        migrations.AddField(
            model_name="readfeedentryusermapping",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.User"
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.User"
            ),
        ),
        migrations.AddField(
            model_name="mylogin",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.User"
            ),
        ),
        migrations.AddField(
            model_name="googlelogin",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.User"
            ),
        ),
        migrations.AddField(
            model_name="feedusercategorymapping",
            name="user_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.UserCategory"
            ),
        ),
        migrations.AddField(
            model_name="feedtagmapping",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.Tag"
            ),
        ),
        migrations.AddField(
            model_name="feedsubscriptionprogressentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.User"
            ),
        ),
        migrations.AddField(
            model_name="feedentrytagmapping",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.Tag"
            ),
        ),
        migrations.AddField(
            model_name="favoritefeedentryusermapping",
            name="feed_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.FeedEntry"
            ),
        ),
        migrations.AddField(
            model_name="favoritefeedentryusermapping",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.User"
            ),
        ),
        migrations.AddField(
            model_name="facebooklogin",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.User"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercategory",
            unique_together={("user", "text")},
        ),
        migrations.AlterUniqueTogether(
            name="subscribedfeedusermapping",
            unique_together={("user", "feed"), ("user", "custom_feed_title")},
        ),
        migrations.AlterUniqueTogether(
            name="readfeedentryusermapping",
            unique_together={("feed_entry", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="feedusercategorymapping",
            unique_together={("feed", "user_category")},
        ),
        migrations.AlterUniqueTogether(
            name="feedtagmapping",
            unique_together={("feed", "tag")},
        ),
        migrations.AlterUniqueTogether(
            name="feedentrytagmapping",
            unique_together={("feed_entry", "tag")},
        ),
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(fields=["id"], name="api_feedent_id_6f9c14_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="favoritefeedentryusermapping",
            unique_together={("feed_entry", "user")},
        ),
    ]
