# Generated by Django 4.2.3 on 2023-07-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_postgres_search_vector"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(
                fields=["-published_at"], name="api_feedent_publish_bdf95e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(
                fields=["-created_at"], name="api_feedent_created_6bb194_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(
                fields=["-updated_at"], name="api_feedent_updated_a08585_idx"
            ),
        ),
    ]
