# Generated by Django 4.2.3 on 2023-08-17 04:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_feed_archive_update_backoff_until_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Captcha",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("seed", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
    ]
