# Generated by Django 4.2.5 on 2023-09-07 22:57

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    User = apps.get_model("api", "User")
    for user in User.objects.all().iterator():
        user.read_feed_entries_counter = user.read_feed_entries.count()
        user.save(update_fields=("read_feed_entries_counter",))


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_captcha"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="read_feed_entries_counter",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
