# Generated by Django 4.2.5 on 2023-09-12 21:52

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from lingua import Language


def _forwards_func(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    Language_ = apps.get_model("api", "Language")

    Language_.objects.create(
        iso639_3="UND", name="UNDEFINED"
    )  # from https://en.wikipedia.org/wiki/ISO_639-3#Special_codes
    Language_.objects.bulk_create(
        Language_(
            iso639_3=lang.iso_code_639_3.name,
            name=lang.name,
        )
        for lang in Language.all()
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_user_read_feed_entries_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "iso639_3",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.RunPython(_forwards_func, migrations.RunPython.noop),
        migrations.CreateModel(
            name="FeedEntryLanguageMapping",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("confidence", models.FloatField()),
                (
                    "feed_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.feedentry"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.language"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedentry",
            name="languages",
            field=models.ManyToManyField(
                related_name="feed_entries",
                through="api.FeedEntryLanguageMapping",
                to="api.language",
            ),
        ),
    ]
