# Generated by Django 3.2 on 2021-04-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20210401_0502"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeedEntryTagMapping",
        ),
    ]
