# Generated by Django 4.2.5 on 2023-09-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_language_feedentrylanguagemapping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedentry",
            name="languages",
        ),
        migrations.AddField(
            model_name="feedentry",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feed_entries",
                to="api.language",
            ),
        ),
        migrations.DeleteModel(
            name="FeedEntryLanguageMapping",
        ),
    ]
