# Generated by Django 3.2.3 on 2021-05-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_auto_20210410_1826"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="attributes",
            field=models.JSONField(default=dict),
        ),
    ]
