# Generated by Django 4.2.5 on 2023-09-14 18:14

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from lingua import Language


def _forwards_func(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    Language_ = apps.get_model("api", "Language")

    iso639_3to1_mappings: dict[str, str] = {
        l.iso_code_639_3.name: l.iso_code_639_1.name for l in Language.all()
    }

    Language_.objects.filter(iso639_3="UND").update(iso639_1="UN")
    for lang in Language_.objects.exclude(iso639_3="UND"):
        lang.iso639_1 = iso639_3to1_mappings[lang.iso639_3]
        lang.save(update_fields=("iso639_1",))


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_feedentry_languages_feedentry_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="iso639_1",
            field=models.CharField(default="", max_length=2),
            preserve_default=False,
        ),
        migrations.RunPython(_forwards_func, migrations.RunPython.noop),
    ]
