# Generated by Django 4.2.5 on 2023-09-19 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={"verbose_name": "Token", "verbose_name_plural": "Tokens"},
        ),
    ]
