# Generated by Django 4.2.5 on 2023-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_feedentry_has_top_image_been_processed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="top_image_processing_attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
