# Generated by Django 4.2.6 on 2023-10-31 03:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_feedentry_top_image_processing_attempt_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassifierLabel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ClassifierLabelFeedEntryCalculated",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassifierLabelFeedEntryVote",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="feedentry",
            name="unique__feed__url__when__updated_at__null",
        ),
        migrations.RemoveConstraint(
            model_name="feedentry",
            name="unique__feed__url__when__updated_at__not_null",
        ),
        migrations.AlterUniqueTogether(
            name="readfeedentryusermapping",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="subscribedfeedusermapping",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="usercategory",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="feedentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("updated_at__isnull", True)),
                fields=("feed", "url"),
                name="feedentry__unique__feed__url__when__updated_at__null",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedentry",
            constraint=models.UniqueConstraint(
                fields=("feed", "url", "updated_at"),
                name="feedentry__unique__feed__url__when__updated_at__not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="readfeedentryusermapping",
            constraint=models.UniqueConstraint(
                fields=("feed_entry", "user"),
                name="readfeedentryusermapping__unique__feed_entry__user",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscribedfeedusermapping",
            constraint=models.UniqueConstraint(
                fields=("user", "feed"), name="unique__user__feed"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscribedfeedusermapping",
            constraint=models.UniqueConstraint(
                fields=("user", "custom_feed_title"),
                name="subscribedfeedusermapping__unique__user__custom_feed_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercategory",
            constraint=models.UniqueConstraint(
                fields=("user", "text"), name="usercategory__unique__user__text"
            ),
        ),
        migrations.AddField(
            model_name="classifierlabelfeedentryvote",
            name="classifier_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.classifierlabel"
            ),
        ),
        migrations.AddField(
            model_name="classifierlabelfeedentryvote",
            name="feed_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.feedentry"
            ),
        ),
        migrations.AddField(
            model_name="classifierlabelfeedentryvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="classifierlabelfeedentrycalculated",
            name="classifier_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.classifierlabel"
            ),
        ),
        migrations.AddField(
            model_name="classifierlabelfeedentrycalculated",
            name="feed_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.feedentry"
            ),
        ),
        migrations.AddConstraint(
            model_name="classifierlabel",
            constraint=models.UniqueConstraint(
                fields=("text",), name="classifierlabel__unique__text"
            ),
        ),
        migrations.AddConstraint(
            model_name="classifierlabelfeedentryvote",
            constraint=models.UniqueConstraint(
                fields=("classifier_label", "feed_entry", "user"),
                name="classifierlabelfeedentryvote__unique__classifier_label__feed_entry__user",
            ),
        ),
        migrations.AddConstraint(
            model_name="classifierlabelfeedentrycalculated",
            constraint=models.UniqueConstraint(
                fields=("classifier_label", "feed_entry"),
                name="classifierlabelfeedentrycalculated__unique__classifier_label__feed_entry",
            ),
        ),
    ]
