# Generated by Django 4.2.6 on 2023-10-31 02:34

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

_label_texts = [
    "Programming",
    "Anime & Manga",
    "News",
    "Linux",
    "Music",
    "Technology",
    "Gaming",
]


def _forward_func_add_initial_classifier_labels(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
):
    ClassifierLabel = apps.get_model("api", "ClassifierLabel")
    ClassifierLabel.objects.bulk_create(
        ClassifierLabel(text=label_text) for label_text in _label_texts
    )


def _reverse_func_add_initial_classifier_labels(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
):
    ClassifierLabel = apps.get_model("api", "ClassifierLabel")
    ClassifierLabel.objects.filter(text__in=_label_texts).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_classifierlabel_classifierlabelfeedentrycalculated_and_more"),
    ]

    operations = [
        migrations.RunPython(
            _forward_func_add_initial_classifier_labels,
            _reverse_func_add_initial_classifier_labels,
        )
    ]
