# Generated by Django 4.2.6 on 2023-11-03 16:54

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_auto_20231031_0358"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassifierLabelFeedCalculated",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ClassifierLabelUserCalculated",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="classifierlabelfeedentrycalculated",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedentry",
            name="calculated_classifier_labels",
            field=models.ManyToManyField(
                related_name="calculated_feed_entry_set",
                through="api.ClassifierLabelFeedEntryCalculated",
                to="api.classifierlabel",
            ),
        ),
        migrations.AddField(
            model_name="feedentry",
            name="voted_classifier_labels",
            field=models.ManyToManyField(
                related_name="voted_feed_entry_set",
                through="api.ClassifierLabelFeedEntryVote",
                to="api.classifierlabel",
            ),
        ),
        migrations.AddIndex(
            model_name="classifierlabelfeedentrycalculated",
            index=models.Index(
                fields=["expires_at"], name="api_classif_expires_353996_idx"
            ),
        ),
        migrations.AddField(
            model_name="classifierlabelusercalculated",
            name="classifier_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.classifierlabel"
            ),
        ),
        migrations.AddField(
            model_name="classifierlabelusercalculated",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="classifierlabelfeedcalculated",
            name="classifier_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.classifierlabel"
            ),
        ),
        migrations.AddField(
            model_name="classifierlabelfeedcalculated",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.feed"
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="calculated_classifier_labels",
            field=models.ManyToManyField(
                related_name="calculated_feed_set",
                through="api.ClassifierLabelFeedCalculated",
                to="api.classifierlabel",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="calculated_classifier_labels",
            field=models.ManyToManyField(
                related_name="calculated_user_set",
                through="api.ClassifierLabelUserCalculated",
                to="api.classifierlabel",
            ),
        ),
        migrations.AddIndex(
            model_name="classifierlabelusercalculated",
            index=models.Index(
                fields=["expires_at"], name="api_classif_expires_5a0f45_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="classifierlabelusercalculated",
            constraint=models.UniqueConstraint(
                fields=("classifier_label", "user"),
                name="classifierlabelusercalculated__unique__classifier_label__user",
            ),
        ),
        migrations.AddIndex(
            model_name="classifierlabelfeedcalculated",
            index=models.Index(
                fields=["expires_at"], name="api_classif_expires_cad114_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="classifierlabelfeedcalculated",
            constraint=models.UniqueConstraint(
                fields=("classifier_label", "feed"),
                name="classifierlabelfeedcalculated__unique__classifier_label__feed",
            ),
        ),
    ]
