# Generated by Django 4.2.7 on 2023-11-06 00:59

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def _forward_func_update_classifier_labels(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
):
    ClassifierLabel = apps.get_model("api", "ClassifierLabel")
    ClassifierLabel.objects.filter(text="Technology").update(
        text="Science & Technology"
    )
    ClassifierLabel.objects.filter(text="Celebrity Culture").update(
        text="Celebrities & Culture"
    )
    ClassifierLabel.objects.filter(text="Business & Finance").update(
        text="Business, Finance & Banking"
    )
    ClassifierLabel.objects.create(text="Computer Hardware & Software")


def _reverse_func_update_classifier_labels(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
):
    ClassifierLabel = apps.get_model("api", "ClassifierLabel")
    ClassifierLabel.objects.filter(text="Science & Technology").update(
        text="Technology"
    )
    ClassifierLabel.objects.filter(text="Celebrities & Culture").update(
        text="Celebrity Culture"
    )
    ClassifierLabel.objects.filter(text="Business, Finance & Banking").update(
        text="Business & Finance"
    )
    ClassifierLabel.objects.filter(text="Computer Hardware & Software").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_classifierlabelfeedcalculated_and_more"),
    ]

    operations = [
        migrations.RunPython(
            _forward_func_update_classifier_labels,
            _reverse_func_update_classifier_labels,
        )
    ]
