# Generated by Django 5.0 on 2024-01-05 17:40


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_auto_20240105_1815"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feedentry",
            name="feedentry__unique__feed__url__when__updated_at__null",
        ),
        migrations.RemoveConstraint(
            model_name="feedentry",
            name="feedentry__unique__feed__url__when__updated_at__not_null",
        ),
        migrations.AddConstraint(
            model_name="feedentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("updated_at__isnull", True)),
                fields=("feed", "id"),
                name="feedentry__unique__feed__id__when__updated_at__null",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedentry",
            constraint=models.UniqueConstraint(
                fields=("feed", "id", "updated_at"),
                name="feedentry__unique__feed__id__updated_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("id__isnull", True), ("updated_at__isnull", True)),
                fields=("feed", "url"),
                name="feedentry__unique__feed__url__when__id__null__updated_at__null",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("id__isnull", True)),
                fields=("feed", "url", "updated_at"),
                name="feedentry__unique__feed__url__updated_at__when__id__null",
            ),
        ),
    ]
