# Generated by Django 5.0.1 on 2024-02-02 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0020_remove_feedentry_feedentry__unique__feed__url__when__updated_at__null_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feedentry",
            name="api_feedent_id_6f9c14_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedentry",
            name="api_feedent_url_a60cf6_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedentry",
            name="api_feedent_created_6bb194_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedentry",
            name="api_feedent_updated_a08585_idx",
        ),
    ]
