# Generated by Django 5.0.1 on 2024-02-06 05:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_remove_feedentry_api_feedent_id_6f9c14_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternateFeedURL",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("feed_url", models.TextField(unique=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.feed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DuplicateFeedSuggestion",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("is_ignored", models.BooleanField(default=False)),
                (
                    "feed1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_feed_suggestions_1",
                        to="api.feed",
                    ),
                ),
                (
                    "feed2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_feed_suggestions_2",
                        to="api.feed",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="duplicatefeedsuggestion",
            constraint=models.CheckConstraint(
                check=models.Q(("feed1_id__lt", models.F("feed2_id")), _negated=True),
                name="check__feed1_id__feed2_id__lessthan",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicatefeedsuggestion",
            constraint=models.UniqueConstraint(
                fields=("feed1", "feed2"), name="unique__feed1__feed2"
            ),
        ),
    ]
