# Generated by Django 5.0.1 on 2024-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alternatefeedurl_duplicatefeedsuggestion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternatefeedurl",
            name="feed_url",
            field=models.URLField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name="feed",
            name="feed_url",
            field=models.URLField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name="feed",
            name="home_url",
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="author_name",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="id",
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="top_image_src",
            field=models.URLField(default="", max_length=2048),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="url",
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="feedsubscriptionprogressentrydescriptor",
            name="custom_feed_title",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="feedsubscriptionprogressentrydescriptor",
            name="feed_url",
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="feedsubscriptionprogressentrydescriptor",
            name="user_category_text",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="subscribedfeedusermapping",
            name="custom_feed_title",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="usercategory",
            name="text",
            field=models.CharField(max_length=1024),
        ),
    ]
