# Generated by Django 5.0.1 on 2024-02-06 20:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_alter_alternatefeedurl_feed_url_alter_feed_feed_url_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alternatefeedurl",
            index=models.Index(
                django.db.models.functions.text.Upper("feed_url"),
                name="idx__alter...__feed_url__upper",
            ),
        ),
        migrations.AddIndex(
            model_name="feed",
            index=models.Index(
                django.db.models.functions.text.Upper("feed_url"),
                name="idx__feed__feed_url__upper",
            ),
        ),
    ]
