# Generated by Django 5.0.1 on 2024-02-06 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0025_remove_duplicatefeedsuggestion_check__feed1_id__feed2_id__lessthan_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="alternatefeedurl",
            name="alter...__idx__feed_url__upper",
        ),
        migrations.RemoveIndex(
            model_name="feed",
            name="feed__idx__feed_url__upper",
        ),
    ]
