# Generated by Django 5.0.2 on 2024-03-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_remove_alternatefeedurl_alter___idx__feed_url__upper_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(
                fields=["-created_at"], name="api_feedent_created_6bb194_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(
                fields=["-updated_at"], name="api_feedent_updated_a08585_idx"
            ),
        ),
    ]
