# Generated by Django 5.0.2 on 2024-03-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_feedentry_api_feedent_created_6bb194_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
