# Generated by Django 5.0.2 on 2024-03-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_user_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="consecutive_update_fail_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
