# Generated by Django 5.0.3 on 2024-06-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_alter_feed_db_updated_at_alter_feed_home_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedentry",
            name="id",
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
