# Generated by Django 5.0.3 on 2024-06-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_alter_feedentry_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="home_url",
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="author_name",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
