# Generated by Django 5.0.7 on 2024-07-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_alter_feed_home_url_alter_feedentry_author_name_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(
                fields=["feed_id", "-published_at", "-created_at", "-updated_at"],
                name="api_feedent_feed_id_60836a_idx",
            ),
        ),
    ]
