# Generated by Django 5.0.7 on 2024-08-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_feedentry_api_feedent_feed_id_60836a_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(
                fields=["feed_id", "is_archived"], name="api_feedent_feed_id_355d0c_idx"
            ),
        ),
    ]
