# Generated by Django 5.1.1 on 2024-09-19 02:41

import uuid_extensions.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_feedentry_api_feedent_feed_id_355d0c_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternatefeedurl",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="captcha",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="classifierlabel",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="classifierlabelfeedcalculated",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="classifierlabelfeedentrycalculated",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="classifierlabelfeedentryvote",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="classifierlabelusercalculated",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="duplicatefeedsuggestion",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="feedsubscriptionprogressentry",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="feedsubscriptionprogressentrydescriptor",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="readfeedentryusermapping",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="subscribedfeedusermapping",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="usercategory",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
    ]
