# Generated by Django 5.1.7 on 2025-04-21 00:32

import django.db.models.deletion
import uuid_extensions.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_alter_alternatefeedurl_uuid_alter_captcha_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemovedFeed",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7, primary_key=True, serialize=False
                    ),
                ),
                ("feed_url", models.URLField(max_length=2048, unique=True)),
                ("reason", models.TextField(blank=True)),
                ("removed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeedEntryReport",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.CharField(max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_ignored", models.BooleanField(default=False)),
                (
                    "feed_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.feedentry"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_ignored"], name="api_feedent_is_igno_0654e3_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedReport",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.CharField(max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_ignored", models.BooleanField(default=False)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.feed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_ignored"], name="api_feedrep_is_igno_7e4bd5_idx"
                    )
                ],
            },
        ),
    ]
