# Generated by Django 5.2.5 on 2025-09-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_removedfeed_feedentryreport_feedreport"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(fields=["url"], name="api_feedent_url_a60cf6_idx"),
        ),
    ]
