# Generated by Django 6.0.3 on 2026-08-12 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_feedentry_api_feedent_url_a60cf6_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifierlabelfeedcalculated",
            name="weight",
            field=models.FloatField(
                default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AddField(
            model_name="classifierlabelfeedentrycalculated",
            name="weight",
            field=models.FloatField(
                default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AddField(
            model_name="classifierlabelusercalculated",
            name="weight",
            field=models.FloatField(
                default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
