# Generated by Django 6.0.7 on 2026-08-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_classifierlabelfeedcalculated_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="classifier_model_fingerprint",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="model_fingerprint of the classifier artifact that last labelled this entry. Empty means never labelled. Deliberately a fingerprint rather than a boolean (cf. has_top_image_been_processed) so that shipping a new model invalidates every entry automatically instead of needing a manual reset.",
                max_length=64,
            ),
        ),
    ]
