version: 2.1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
jobs:
  build:
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - run:
          name: remove unneeded files
          command: |
            rm -r api/tests/
      - run:
          name: tarball
          command: tar -czf build.tar.gz rss_temple api manage.py
      - store_artifacts:
          path: ~/build.tar.gz
  test:
    docker:
      - image: circleci/python:3.11.3
        environment:
          PIPENV_VERBOSITY: -1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "Pipfile.lock" }}
      - run:
          name: pipenv setup
          command: |
            pip install -U pip
            pip install -U pipenv
      - run:
          name: pipenv install
          command: pipenv sync --dev
      - save_cache:
          key: dependency-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.local/share/virtualenvs/"
            - "~/.pyenv/"
      - run:
          name: tests
          command: pipenv run coverage run manage.py test --exclude-tag=remote api.tests
          environment:
            TEST_RUNNER_TYPE: xml
            TEST_OUTPUT_VERBOSE: 2
      - store_test_results:
          path: ~/rss_temple/test-results/
      - store_artifacts:
          path: ~/rss_temple/test-results/
      - run:
          name: codecov
          command: pipenv run codecov -X gcov
