# Generated by Django 2.0.4 on 2018-04-21 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('feed_url', models.TextField(unique=True)),
                ('is_new', models.BooleanField(default=True)),
                ('title', models.TextField(null=True)),
                ('home_url', models.TextField(null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('title', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('author_name', models.TextField(null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='FeedEntryTagMapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('feed_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeedEntry')),
            ],
        ),
        migrations.CreateModel(
            name='FeedTagMapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedFeedUserMapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label_text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookLogin',
            fields=[
                ('login_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Login')),
            ],
            bases=('api.login',),
        ),
        migrations.CreateModel(
            name='MyLogin',
            fields=[
                ('login_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Login')),
                ('pw_hash', models.CharField(max_length=96)),
            ],
            bases=('api.login',),
        ),
        migrations.AddField(
            model_name='subscribedfeedusermapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='feedtagmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tag'),
        ),
        migrations.AddField(
            model_name='feedentrytagmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='subscribedfeedusermapping',
            unique_together={('feed', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='feedtagmapping',
            unique_together={('feed', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='feedentrytagmapping',
            unique_together={('feed_entry', 'tag')},
        ),
        migrations.AddIndex(
            model_name='feedentry',
            index=models.Index(fields=['id'], name='api_feedent_id_6f9c14_idx'),
        ),
    ]
