# Generated by Django 2.0.2 on 2018-02-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64)),
                ('pw_hash', models.CharField(max_length=96)),
            ],
        ),
    ]
