# Generated by Django 3.1.5 on 2021-01-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notifyemailqueueentry_notifyemailqueueentryrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedentry',
            name='hash',
            field=models.BigIntegerField(),
        ),
    ]
