# Generated by Django 3.1.5 on 2021-01-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210114_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedentry',
            name='hash',
            field=models.BinaryField(max_length=64),
        ),
    ]
