# Generated by Django 3.1.5 on 2021-01-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210114_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedentry',
            name='hash',
            field=models.BinaryField(db_index=True, max_length=64),
        ),
    ]
