# Generated by Django 3.1.5 on 2021-01-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210114_0615'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedentry',
            index=models.Index(fields=['hash'], name='api_feedent_hash_5fbffa_idx'),
        ),
    ]
