# Generated by Django 3.2 on 2021-04-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_feedentrytagmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedTagMapping',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
